openapi: 3.0.0
info:
  title: Betting system REST API
  version: 1.0.0
  description: REST API.

servers:
  - url: /api
    description: Primary API server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter the Access Token in the format: Bearer <token>

  schemas:
    Account:
      type: object
      properties:
        name:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        birthdate:
          type: string
          example: 2000-11-01
        phone_number:
          type: string
          example: 555-1234
        email:
          type: string
          format: email
          example: user@example.com
        password: { type: string, format: password, example: securepassword123 }
      required:
        - name
        - lastname
        - email
        - password
    Me:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        age:
          type: integer
          example: 30
        phone_number:
          type: string
          example: 555-1234
        email:
          type: string
          format: email
          example: user@example.com
      required:
        - name
        - lastname
        - email
        - password
    LoginInput:
      type: object
      properties:
        email: { type: string, format: email, example: user@example.com }
        password: { type: string, format: password, example: securepassword123 }
      required:
        - email
        - password
    TokenResponse:
      type: object
      properties:
        message: { type: string }
        accessToken: { type: string }
        refreshToken: { type: string }


paths:
  /register:
    post:
      summary: Create a new user account
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        201: { description: Account created successfully. }
        409: { description: Email already in use. }

  /login:
    post:
      summary: Authenticate user and get tokens
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        200:
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        401: { description: Invalid credentials. }

  /token:
    post:
      summary: Generate a new access token using a valid refresh token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken: { type: string }
      responses:
        200: { description: New access token generated successfully. }
        403: { description: Invalid, expired, or unrecognized refresh token. }

  /logout:
    delete:
      summary: Log out the current user and invalidate refresh token
      tags: [Auth]
      security:
        - BearerAuth: []
      responses:
        200: { description: Logged out successfully. }
        401: { description: Access denied (No token provided). }

  /me:
    get:
      summary: Get data of the current logged user
      tags: [Account]
      security:
        - BearerAuth: []
      responses:
        200:
          description: User data retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
        401: { description: Access denied. }
